Numpy : Practice Problem

In [1]:
import numpy as np
import matplotlib.pyplot as plt

1. Extract all odd numbers from arr


In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

2. Replace all odd numbers in arr with -1

In [3]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


3. Convert a 1D array to a 2D array with 2 rows

In [4]:
arr=np.arange(10)
np.reshape(arr,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

4. Stack arrays a and b vertically

In [5]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print('Here two arrays are stacked vertically:\n',np.vstack((a,b)))

Here two arrays are stacked vertically:
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


5. Get all items between 5 and 10 from a

In [6]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>5)&(a<=10)]

array([ 6,  9, 10])

Desired Output:
(array([6, 9, 10]),)

6. Create a null vector of size 10 but the fifth value which is 1.

In [7]:
arr = np.zeros(10)
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49.

In [8]:
arr = np.arange(10,49)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

8. Create a 10x10 array with random values and find the minimum and maximum values.

In [9]:
arr = np.random.randint(1,1000,(10,10))
print('Original array is:\n',arr)
print(np.max(arr))
print(np.min(arr))

Original array is:
 [[244 313 363 108 294  38 673 209  24 690]
 [211 866 882  32 867 307 216 903 341 390]
 [553 644 727 588 597 290 680 182 628 210]
 [189 928 697 445 933 847 705 777 479 619]
 [389  64 628 575 539 402 490 333 870 718]
 [300 533 380  67 214 910 152 347 182 173]
 [857 261 394 824  64 266 943 227 325 337]
 [546 514 512 469 249  81 892  51 240 826]
 [460 985 613 261 277 390 107 858 233 137]
 [478 780 262  12 153 190 664 653 578  80]]
985
12


9. Create a 3*3 matrix and print it's transpose matrix

In [10]:
arr = np.random.randint(10,20,(3,3))
print('Original Matrix is:\n',arr)
print()
print('Transpose of the above matrix is:\n',np.transpose(arr))

Original Matrix is:
 [[11 12 13]
 [13 17 13]
 [17 13 13]]

Transpose of the above matrix is:
 [[11 13 17]
 [12 17 13]
 [13 13 13]]


10. Create two arrays of 2-D and find dot product of it.

In [11]:
arr1 = np.random.randint(10,40,(3,3))
arr2 = np.random.randint(10,50,(3,3))
print('Matrix 1 is \n:',arr1,"\nand Matrix 2 is : \n",arr2)

print("Dot product is\n",arr1.dot(arr2))

Matrix 1 is 
: [[15 13 37]
 [38 39 10]
 [19 21 39]] 
and Matrix 2 is : 
 [[40 17 20]
 [35 28 40]
 [14 43 34]]
Dot product is
 [[1573 2210 2078]
 [3025 2168 2660]
 [2041 2588 2546]]


11. Compute the maximum for each row in the given array.

In [14]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print('Original Array:\n',a)
a.max(axis=1)

Original Array:
 [[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


array([9, 8, 6, 3, 9])

12. Select 3rd & 5th row and 3rd & 4th columns

In [18]:
data = np.random.randint(10,100,(5,4))
print('Original Array is:\n',data)

print()
print('Required array is:\n',data[2:5,2:4])

Original Array is:
 [[13 58 62 53]
 [46 15 81 48]
 [96 52 94 86]
 [43 68 52 32]
 [10 65 29 63]]

Required array is:
 [[94 86]
 [52 32]
 [29 63]]


13. Convert below matrix into vector

In [20]:
matrix = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
np.reshape(matrix,(1,-1))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

14. The product of two inverse matrix is identical matrix,prove

In [22]:
# create a square matrix
m = np.array([[2,3],
              [2,4]])
n = np.linalg.inv(m)
print('Inverse array is:\n',n)
print()
print('Product is: ',m.dot(n))

Inverse array is:
 [[ 2.  -1.5]
 [-1.   1. ]]

Product is:  [[1. 0.]
 [0. 1.]]


15. Create a matrix from a uniform distribution over [0, 1)

In [24]:
x = np.random.uniform(size=(0, 1))

print(x)


[]
