<h1>Vector of size 10 and Fifth value is 1</h1>

In [2]:
import numpy as np

arr1 = np.zeros(shape=(1,10))
arr1[0,4] = 1
arr1

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

<h1>Vector with values ranging from 10 to 49</h1>

In [9]:
arr2 = np.random.randint(low = 10,high = 50,size = (1,10))
arr2

array([[47, 36, 40, 46, 21, 39, 49, 10, 31, 43]])

<h1>3x3 Matrix with values ranging from 0 to 8</h1>

In [10]:
arr3 = np.random.randint(low = 0,high = 9,size = (3,3))
arr3

array([[1, 8, 6],
       [2, 1, 8],
       [1, 4, 7]])

<h1>Indices of Non Zero Elements</h1>

In [13]:
arr4 = np.array([1,2,0,0,4,0])
np.where(arr4 != 0)[0]

array([0, 1, 4], dtype=int64)

<h1>Min and Max of a 10x10 Array</h1>

In [18]:
arr5 = np.random.randint(low = 1,high = 100,size = (10,10))
print("Numpy array is:\n",arr5)
print()
print('Maximum value in numpy array is:\n',np.max(arr5))
print()
print('Minimum value in numpy array is:\n',np.min(arr5))

Numpy array is:
 [[20 99 84 76 57 10 67 98 26 76]
 [89 84 32 79 14 43 33 84 18 13]
 [87 41 25 28 87 46 43 62  1 38]
 [ 7 68 36 48 37 86 39 48 47 86]
 [31 47 13 26 96 69 85 26  8 18]
 [73 44 64 29 41 10 27 48 84 80]
 [88 70  2 17 13 36 17 57 64 32]
 [59 25 14  8 40 99 44 39 96 64]
 [52  4 34 22 68 31  6 30 37 82]
 [77 49 16 50 35 70 39 59 61 62]]

Maximum value in numpy array is:
 99

Minimum value in numpy array is:
 1


<h1>Mean of an array</h1>

In [4]:
arr6 = np.random.randint(low = 10,high = 51,size = (1,30))
print('Numpy array is:\n',arr6)
print()
print('Mean of numpy array is:',np.mean(arr6))

Numpy array is:
 [[29 48 49 12 32 45 41 21 39 18 27 18 28 16 37 34 12 10 14 29 45 47 33 38
  22 26 45 47 50 41]]

Mean of numpy array is: 31.766666666666666
